Refactor ci-cd-pm2.yml to update PM2 deployment path and start the application with PM2

diff --git a/.github/workflows/ci-cd-pm2.yml b/.github/workflows/ci-cd-pm2.yml
--- a/.github/workflows/ci-cd-pm2.yml
+++ b/.github/workflows/ci-cd-pm2.yml
@@ -5,7 +5,7 @@ on:
 
 jobs:
   build-and-deploy:
-    runs-on: ubuntu-latest 
+    runs-on: ubuntu-latest
     env:
       EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
       EC2_URL: ${{ secrets.EC2_URL }}
@@ -20,7 +20,7 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '18'
+          node-version: "18"
 
       # Step 3: Install dependencies
       - name: Install dependencies
@@ -39,96 +39,100 @@ jobs:
       # Step 6: Deploy to EC2
       - name: Deploy to EC2
         env:
-            MONGO_URL: ${{ secrets.MONGO_URL }}
-            PORT: ${{ secrets.PORT }}
-            NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
-            RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
-            COMPANY_RESEND_GMAIL_ACCOUNT: ${{ secrets.COMPANY_RESEND_GMAIL_ACCOUNT }}
+          MONGO_URL: ${{ secrets.MONGO_URL }}
+          PORT: ${{ secrets.PORT }}
+          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
+          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
+          COMPANY_RESEND_GMAIL_ACCOUNT: ${{ secrets.COMPANY_RESEND_GMAIL_ACCOUNT }}
         run: |
-            echo "Creating app directory on EC2 instance..."
-            ssh -o StrictHostKeyChecking=no -o ConnectTimeout=20 ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }} "mkdir -p ~/app"
-            echo "Copying files to EC2 instance..."
-            rsync -avz --progress ./* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }}:~/app
-            echo "Running deployment script on EC2 instance..."
-            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }} << EOF
-                # Update system and install Node.js if not present
-                sudo apt-get update
-                if ! command -v node &> /dev/null; then
-                curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
-                sudo apt-get install -y nodejs
-                fi
+          echo "Creating app directory on EC2 instance..."
+          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=20 ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }} "mkdir -p ~/app"
+          echo "Copying files to EC2 instance..."
+          rsync -avz --progress ./* ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }}:~/app
+          echo "Running deployment script on EC2 instance..."
+          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }} << EOF
+              # Update system and install Node.js if not present
+              sudo apt-get update
+              if ! command -v node &> /dev/null; then
+              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
+              sudo apt-get install -y nodejs
+              fi
 
-                # Install PM2 globally if not present
-                if ! command -v pm2 &> /dev/null; then
-                sudo npm install -g pm2
-                fi
+              # Install PM2 globally if not present
+              if ! command -v pm2 &> /dev/null; then
+              sudo npm install -g pm2
+              fi
 
-                # Navigate to app directory
-                cd ~/app
+              # Navigate to app directory
+              cd ~/app
 
-                # Install dependencies
-                npm install
+              # Install dependencies
+              npm install
 
-                # Build the project (if applicable)
-                npm run build
+              # Build the project (if applicable)
+              npm run build
 
-                # Set environment variables
-                cat <<EOT > .env
-                MONGO_URL=$MONGO_URL
-                PORT=$PORT
-                NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
-                RESEND_API_KEY=$RESEND_API_KEY
-                COMPANY_RESEND_GMAIL_ACCOUNT=$COMPANY_RESEND_GMAIL_ACCOUNT
-                EOT
+              # Set environment variables
+              cat <<EOT > .env
+              MONGO_URL=$MONGO_URL
+              PORT=$PORT
+              NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
+              RESEND_API_KEY=$RESEND_API_KEY
+              COMPANY_RESEND_GMAIL_ACCOUNT=$COMPANY_RESEND_GMAIL_ACCOUNT
+              EOT
 
-                # Export environment variables
-                export MONGO_URL=$MONGO_URL
-                export PORT=$PORT
-                export NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
-                export RESEND_API_KEY=$RESEND_API_KEY
-                export COMPANY_RESEND_GMAIL_ACCOUNT=$COMPANY_RESEND_GMAIL_ACCOUNT
+              # Export environment variables
+              export MONGO_URL=$MONGO_URL
+              export PORT=$PORT
+              export NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
+              export RESEND_API_KEY=$RESEND_API_KEY
+              export COMPANY_RESEND_GMAIL_ACCOUNT=$COMPANY_RESEND_GMAIL_ACCOUNT
 
-                # Start or restart the application with PM2
-                sudo pm2 start ecosystem.config.cjs --env production || sudo pm2 restart ecosystem.config.cjs --env production 
+              # Start the application with PM2
+              pm2 stop app
+              pm2 start src/app.ts --name "app" --interpreter "tsx" --env production
 
-                # Save PM2 process list and set to start on boot
-                sudo pm2 save
-                sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u $USER --hp /home/$USER
+              # Verify the process is running
+              pm2 list
 
-                # Install Nginx if not present
-                if ! command -v nginx &> /dev/null; then
-                  sudo apt-get install -y nginx
-                fi
+              # Save PM2 process list and set to start on boot
+              pm2 save
+              sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u $USER --hp /home/$USER
 
-                # Create Nginx configuration
-                sudo tee /etc/nginx/sites-available/default > /dev/null << EOL
-                server {
-                    listen 80;
-                    server_name ${{ secrets.EC2_URL }};
-                
-                    location / {
-                        proxy_pass http://localhost:$PORT;
-                        proxy_http_version 1.1;
-                        proxy_set_header Upgrade \$http_upgrade;
-                        proxy_set_header Connection 'upgrade';
-                        proxy_set_header Host \$host;
-                        proxy_cache_bypass \$http_upgrade;
-                    }
-                }
-                EOL
+              # Install Nginx if not present
+              if ! command -v nginx &> /dev/null; then
+                sudo apt-get install -y nginx
+              fi
 
-                # Restart Nginx
-                sudo systemctl restart nginx
+              # Create Nginx configuration
+              sudo tee /etc/nginx/sites-available/default > /dev/null << EOL
+              server {
+                  listen 80;
+                  server_name ${{ secrets.EC2_URL }};
+              
+                  location / {
+                      proxy_pass http://localhost:$PORT;
+                      proxy_http_version 1.1;
+                      proxy_set_header Upgrade \$http_upgrade;
+                      proxy_set_header Connection 'upgrade';
+                      proxy_set_header Host \$host;
+                      proxy_cache_bypass \$http_upgrade;
+                  }
+              }
+              EOL
 
-                # Clean up
-                npm cache clean --force
-                sudo apt-get clean
-                sudo rm -rf /var/lib/apt/lists/*
-    
-                echo "Cleaning up log files..."
-                sudo find /var/log/ -type f -name "*.log" -exec truncate -s 0 {} +
-    
-                echo "Checking disk usage after cleanup..."
-                df -h
-    
-            EOF
+              # Restart Nginx
+              sudo systemctl restart nginx
+
+              # Clean up
+              npm cache clean --force
+              sudo apt-get clean
+              sudo rm -rf /var/lib/apt/lists/*
+
+              echo "Cleaning up log files..."
+              sudo find /var/log/ -type f -name "*.log" -exec truncate -s 0 {} +
+
+              echo "Checking disk usage after cleanup..."
+              df -h
+
+          EOF
